#!/bin/bash

# make vhost

red='\e[0;31m'

SCRIPTNAME=$(basename $0)

PATHENABLED="/etc/apache2/sites-enabled"
PATHAVAILABLE="/etc/apache2/sites-available"
SERVERADMIN="webmaster@localhost"

error_exit () {
    echo -e "${red}ERROR: $1" 1>&2
    exit 1
}

show_enabled () {

    echo "List of all enabled Virtual Hosts $SCRIPTNAME"
    echo "---------------------------------------------"
    ls -1 $PATHENABLED
}
    
add_vhost () {
    # echo "$PATHAVAILABLE/$2"
    FILEPATH=
    FILENAME=
    

    if [[ ! -z $4 ]]; then 
        FILENAME=$4 
        FILEPATH="$PATHAVAILABLE/$4"
    else
        FILENAME=$2
        FILEPATH="$PATHAVAILABLE/$2"
    fi

    # Check if file exists
    if [[ -f $FILEPATH ]]; then
        error_exit "File $FILEPATH exists. Try a different name"
    fi

    echo -e "--Creating $FILEPATH with"
    echo -e "  ServerName: $2"
    echo -e "  DocumentRoot $3"


    cat <<- _EOF_ > $FILEPATH
<VirtualHost *:80>
    ServerAdmin $SERVERADMIN
    ServerName $2

    DocumentRoot $3
    <Directory />
        Options Indexes FollowSymLinks
        AllowOverride All
    </Directory>

    ErrorLog \${APACHE_LOG_DIR}/error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
_EOF_
    echo "FILE: $FILEPATH has been created"

    a2ensite $FILENAME
    echo "-----------------------------------------"
    service apache2 reload
    echo "-----------------------------------------"
    echo "VirtualHost created"
    echo "-----------------------------------------"
    echo "Adding server name to /etc/hosts"
    echo "127.0.0.1   $2" >> /etc/hosts


    return
}

remove_vhost () {
    echo "disabling $1"

    a2dissite $1
    if [ "$?" -ne 0 ]
    then
        error_exit "Cannot disable $1"
    fi

    if [ ! -f "$PATHAVAILABLE/$1" ]
    then
        error_exit "$1 does not exist"
    fi

    echo "removing $1"
    rm "$PATHAVAILABLE/$1"

    if [ "$?" -ne 0 ]
    then
        error_exit "Disabled $? but could not remove $?"
    fi

    service apache2 reload
    echo "Disabled and removed $1"
    echo "DONE"
}

usage () {
    echo "
Usage:
  makevhost [ commands ]

Available commands:
  show: show enabled virtual hosts
  create: filename defaults to servername.
    arguments:
      servername documentroot [ filename ]
  remove: removes existing virtual hosts
    arguments:
      filename
    "
}

# Check for root access

if [[ ! -d $PATHAVAILABLE ]]; then
    error_exit "\*$PATHAVAILABLE does not exists"
fi

case $1 in
    show)   show_enabled
            exit
            ;;
    create) echo -e "*Creating vhost...\n"
        if [ -z $2 ] || [ -z $3 ]; then
            error_exit "server name and/or document root missing"
        else
            if [ $(id -u) -ne 0 ]; then
                error_exit "Need root access.  Use sudo."
            fi
            add_vhost "$@"
        fi
        ;;
    remove) 
        if [[ -z "$2" ]]
        then
            error_exit "Need to provide vhost name"
        fi
        remove_vhost "$2"
        exit
        ;;
    *) usage
        exit
        ;;
esac

